**Linear Algebra**

In [ ]:
import numpy as np

In [ ]:
x = 25.0
x

25.0

In [ ]:
type(x) # For more specificity (e.g., int16, uint8), NumPy or another numeric library

float

In [ ]:
y = 5

In [ ]:
py_sum = x + y
py_sum

30.0

In [ ]:
type(py_sum)

float

In [ ]:
x_float=25.0
x_float=x_float + y
x_float

30.0

In [ ]:
type(x_float)

float

**Scalars in Pytorch**

In [ ]:
import torch

In [ ]:
X_pt=torch.tensor(25)
X_pt

tensor(25)

In [ ]:
X_pt.shape

torch.Size([])

In [ ]:
e_pt=torch.tensor(30.5)
e_pt

tensor(30.5000)

**Scalars in TensorFlow**



In [ ]:
import tensorflow as tf

In [ ]:
f_tf=tf.Variable(20)
f_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [ ]:
f_tf.shape

TensorShape([])

In [ ]:
i_tf=tf.Variable(10)
i_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [ ]:
tf_Sum=f_tf + i_tf
tf_Sum

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
type(tf_Sum.numpy())

numpy.int32

In [ ]:
f_tf + i_tf

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
type(tf_Sum.numpy())

numpy.int32

In [ ]:
tf_float=tf.Variable(15,dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=15.0>

**Vectors (Rank 1 Tensors) in NumPy**

In [ ]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
x.shape

(3,)

In [ ]:
len(x)

3

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x[2]

3

In [ ]:
x[1]

2

In [ ]:
x[0]

1

In [ ]:
type(x[2])

numpy.int64

**Vector Transposition**

In [ ]:
x_t=x.T
x_t

array([1, 2, 3])

In [ ]:
x_t.shape

(3,)

In [ ]:
y=np.array([[1,2,3]])
y

array([[1, 2, 3]])

In [ ]:
y_t=y.T
y_t

array([[1],
       [2],
       [3]])

In [ ]:
y_t.T


array([[1, 2, 3]])

In [ ]:
y_t.shape

(3, 1)

**Zero Vectors**


**Have no effect if added to another vector**

In [ ]:
z=np.zeros(4)
z

array([0., 0., 0., 0.])

In [ ]:
z.shape

(4,)

In [ ]:
type(z)

numpy.ndarray

**Vectors in PyTorch and TensorFlow**

In [ ]:
t_tf=tf.Variable([[2,3,4]])
t_tf


<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[2, 3, 4]], dtype=int32)>

In [ ]:
p_pt=torch.tensor([2,4,5])
p_pt

tensor([2, 4, 5])

### $L^2$ Norm

In [ ]:
x

array([1, 2, 3])

In [ ]:
(1**2+2**2+3**2)**(1/2)

3.7416573867739413

In [ ]:
np.linalg.norm(x)

3.7416573867739413

So, if units in this 3-dimensional vector space are meters, then the vector $x$ has a length of 3.8m

### $L^1$ Norm

In [ ]:
x


array([1, 2, 3])

In [ ]:
np.abs(1)+np.abs(2)+np.abs(3)

6

### Squared $L^2$ Norm

In [ ]:
x

array([1, 2, 3])

In [ ]:
(1**2+2**2+3**2)

14

In [ ]:
np.dot(x,x)

14

### Max Norm

In [ ]:
x

array([1, 2, 3])

In [ ]:
np.max([np.abs(1),np.abs(2),np.abs(3)])

3

### Orthogonal Vectors

In [ ]:
i=np.array([[1,0]])
i

array([[1, 0]])

In [ ]:
j=np.array([0,1])
j

array([0, 1])

In [ ]:
i+j

array([[1, 1]])

In [ ]:
np.dot(i,j)


array([0])

### Matrices (Rank 2 Tensors) in NumPy

---



In [ ]:
X=np.array([[2,3],[1,6],[5,8]])
X

array([[2, 3],
       [1, 6],
       [5, 8]])

In [ ]:
X.shape

(3, 2)

In [ ]:
len(X)

3

In [ ]:
X.size

6

In [ ]:
X[0:2, 0:2]

array([[2, 3],
       [1, 6]])

In [ ]:
X[:,0]

array([2, 1, 5])

In [ ]:
X[1,:]

array([1, 6])

### Matrices in PyTorch

In [ ]:
q_pt=torch.tensor([[2,3,4],[4,6,7],[2,5,8]])
q_pt

tensor([[2, 3, 4],
        [4, 6, 7],
        [2, 5, 8]])

In [ ]:
q_pt.size

<function Tensor.size>

In [ ]:
q_pt.shape

torch.Size([3, 3])

In [ ]:
q_pt[1,:]

tensor([4, 6, 7])

### Matrices in TensorFlow

In [ ]:
w_tf=tf.Variable([[1,2,3],[3,4,5],[1,2,3]])
w_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3]], dtype=int32)>

In [ ]:
w_tf.shape

TensorShape([3, 3])

In [ ]:
w_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [ ]:
w_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 2], dtype=int32)>

In [ ]:
w_tf[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
w_tf[2,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
w_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [ ]:
w_tf[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
w_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 1], dtype=int32)>

In [ ]:
w_tf[:,2]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 3], dtype=int32)>

In [ ]:
w_tf.shape

TensorShape([3, 3])

In [ ]:
tf.shape(w_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

### Higher-Rank Tensors

Rank 4 tensors are common for images, where each dimension corresponds to:

1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [ ]:
images_pt = torch.zeros([32, 28, 28, 3])

In [ ]:
images_tf = tf.zeros([32, 28, 28, 3])

## Tensor Operations

### Tensor Transposition

In [ ]:
X

array([[2, 3],
       [1, 6],
       [5, 8]])

In [ ]:
X.T

array([[2, 1, 5],
       [3, 6, 8]])

In [ ]:
X_pt.T

tensor(25)

In [ ]:
X

array([[2, 3],
       [1, 6],
       [5, 8]])

### Basic Arithmetical Properties

In [ ]:
X*3

array([[ 6,  9],
       [ 3, 18],
       [15, 24]])

In [ ]:
X*2+2

array([[ 6,  8],
       [ 4, 14],
       [12, 18]])

In [ ]:
X-2

array([[ 0,  1],
       [-1,  4],
       [ 3,  6]])